<?php
/* @var $container Zend\Navigation\Navigation */
?>
<ul class="<?= $this->navigation($container)->menu()->getUlClass() ?>">
    <?php foreach ($container as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>

    <li<?= (($page->isActive())?' class="active"':'') ?>>
        <a class="nav-header" href="<?= $page->getHref() ?>"<?php if ($page->getTarget() != ''): ?> target="<?= $page->getTarget() ?>"<?php endif; ?>>
            <?php if ($page->get('icon') !== ''): ?>
            <span class="<?= $page->get('icon') ?>"></span>
            <?php endif; ?>
            <?= $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())) ?>

        </a>
    </li>
        <?php else: ?>
            <?php
            // Check if access is allowed for at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get('separator') !== true) {
                    $access = true;
                }
            }
            if ($access):
            ?>
    <li class="dropdown<?= (($page->isActive(true))?' active':'') ?>">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <?php if ($page->get('icon') !== ''): ?>
            <span class="<?= $page->get('icon') ?>"></span>
            <?php endif; ?>
            <?= $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())) ?>
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <?php foreach ($page->getPages() as $child): ?>
                <?php if ($child->get('separator') === true): ?>
            <li class="divider"></li>
                <?php
                        continue;
                    endif;
                ?>
                <?php if (!$this->navigation()->accept($child)) continue; ?>
            <li<?= (($child->isActive())?' class="active"':'') ?>>
                <a href="<?= $child->getHref() ?>"<?php if ($child->getTarget() != ''): ?> target="<?= $child->getTarget() ?>"<?php endif; ?>>
                    <?php if ($child->get('icon') !== ''): ?>
                    <span class="<?= $child->get('icon') ?>"></span>
                    <?php endif; ?>
                    <?= $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())) ?>

                </a>
            </li>
            <?php endforeach ?>
        </ul>
    </li>
            <?php endif; ?>
        <?php endif ?>
    <?php endforeach ?>

</ul>