language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
 - composer install
 - wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/php-coveralls
