<?php
$title = $this->translate('Users');
$this->headTitle($title);
$this->dataTablesInitHelper([
    'table' => '#users',
    'initOptions' => [
        'autoWidth' => false,
    ],
]);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php if ($this->isGranted('users.add')) : ?>
<p>
  <a class="btn btn-default" href="<?= $this->url('users/add') ?>"><i class="fa fa-plus-circle fa-fw" aria-hidden="true"></i> <?= $this->escapeHtml($this->translate('Add new user')) ?></a>
</p>
<?php endif; ?>
<table class="table table-bordered table-striped" id="users">
  <thead>
    <tr>
      <th><?= $this->escapeHtml($this->translate('Username')) ?></th>
      <th><?= $this->escapeHtml($this->translate('Display name')) ?></th>
      <th><?= $this->escapeHtml($this->translate('Email')) ?></th>
<?php if ($this->isGranted('users.viewAll')) : ?>
      <th><?= $this->escapeHtml($this->translate('Role')) ?></th>
<?php endif; ?>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($users as $user) : ?>
    <tr>
      <td>
<?php if ($this->isGranted('users.viewAll')) : ?>
        <i class="fa <?php if ($user->state) : ?>fa-check-circle text-success<?php else : ?>fa-times-circle text-danger<?php endif; ?> fa-fw" aria-hidden="true"></i>
<?php endif; ?>
        <?= $this->escapeHtml($user->username) ?></td>
      <td><?= $this->escapeHtml($user->displayName) ?></td>
      <td><?= $this->escapeHtml($user->email) ?></td>
<?php if ($this->isGranted('users.viewAll')) : ?>
      <td><?= $this->escapeHtml($user->roleId) ?></td>
<?php endif; ?>
      <td>
        <div class="btn-group">
    <?php if ($this->isGranted('users.edit')) : ?>
          <a class="btn btn-default" href="<?= $this->url('users/edit', [
    'userId' => $user->userId,
]) ?>"><i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> <?= $this->escapeHtml($this->translate('Edit')) ?></a>
          <a class="btn btn-default" href="<?= $this->url('users/userlanguages', [
    'userId' => $user->userId,
]) ?>"><i class="fa fa-language fa-fw" aria-hidden="true"></i> <?= $this->escapeHtml($this->translate('Languages')) ?></a>
    <?php endif; ?>
    <?php if ($this->isGranted('users.delete')) : ?>
          <a class="btn btn-danger" href="<?= $this->url('users/delete', [
    'userId' => $user->userId,
]) ?>"><i class="fa fa-minus-circle fa-fw" aria-hidden="true"></i> <?= $this->escapeHtml($this->translate('Delete')) ?></a>
    <?php endif; ?>
        </div>
      </td>
    </tr>
<?php endforeach; ?>
  </tbody>
</table>
