<?php
$title = sprintf($this->translate('Resource files of app "%s"'), $app->name);
$this->headTitle($title);
$this->dataTablesInitHelper([
    'table' => '#appResourceFiles',
    'initOptions' => [
        'autoWidth' => false,
    ],
]);
$count = count($appResourceFiles);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php if ($this->isGranted('appresourcefile.add')) : ?>
<p>
  <a class="btn btn-default" href="<?= $this->url('appresourcefile', [
    'appId'  => $app->id,
    'action' => 'add',
]) ?>"><i class="fa fa-plus-circle fa-fw" aria-hidden="true"></i> <?= $this->escapeHtml($this->translate('Add new app resource file')) ?></a>
</p>
<?php endif; ?>
<table class="table table-bordered table-striped" id="appResourceFiles">
  <thead>
    <tr>
      <th><?= $this->escapeHtml($this->translate('Name')) ?></th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($appResourceFiles as $appResourceFile) : ?>
    <tr>
      <td><?= $this->escapeHtml($appResourceFile->Name) ?></td>
      <td>
        <div class="btn-group">
<?php if ($this->isGranted('appresourcefile.edit')) : ?>
          <a class="btn btn-default" href="<?= $this->url('appresourcefile', [
    'appId'          => $appResourceFile->AppId,
    'action'         => 'edit',
    'resourceFileId' => $appResourceFile->Id,
]) ?>"><i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i> <?= $this->escapeHtml($this->translate('Edit')) ?></a>
<?php endif; ?>
<?php if ($this->isGranted('appresourcefile.delete')) : ?>
          <a class="btn btn-danger" href="<?= $this->url('appresourcefile', [
    'appId'          => $appResourceFile->AppId,
    'action'         => 'delete',
    'resourceFileId' => $appResourceFile->Id]) ?>"><i class="fa fa-minus-circle fa-fw" aria-hidden="true"></i> <?= $this->escapeHtml($this->translate('Delete')) ?></a>
<?php endif; ?>
        </div>
      </td>
    </tr>
<?php endforeach; ?>
  </tbody>
</table>
