<?php
$type = (in_array($type, ['success', 'info', 'warning', 'danger'])) ? $type : 'info';
?>
<div class="alert alert-<?= $type ?> alert-dismissable" role="alert">
<?php if ($this->canClose): ?>
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
<?php endif; ?>
<?php if ($type == 'success'): ?>
  <i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>
  <span class="sr-only"><?= $this->translate('Success:') ?> </span>
<?php elseif ($type == 'info'): ?>
  <i class="fa fa-info-circle fa-fw" aria-hidden="true"></i>
  <span class="sr-only"><?= $this->translate('Info:') ?> </span>
<?php elseif ($type == 'warning'): ?>
  <i class="fa fa-exclamation-triangle fa-fw" aria-hidden="true"></i>
  <span class="sr-only"><?= $this->translate('Warning:') ?> </span>
<?php elseif ($type == 'danger'): ?>
  <i class="fa fa-exclamation-circle fa-fw" aria-hidden="true"></i>
  <span class="sr-only"><?= $this->translate('Error:') ?> </span>
<?php endif; ?>
  <?= $message ?>
</div>
