<?php
$btnClass = ($entry->suggestionCount > 0) ? 'btn-info' : 'btn-default';
$tooltip = sprintf($this->translate('%d suggestions'), $entry->suggestionCount);
?>
<div class="btn-group" role="group">
  <button type="button" class="btn <?= $btnClass ?> translationDetails" data-entryid="<?= $this->escapeHtmlAttr($entry->defaultId) ?>" data-toggle="tooltip" data-placement="right" title="<?= $this->escapeHtmlAttr($tooltip) ?>" role="button"><?= $this->escapeHtml($this->translate('Details')) ?></button>
</div>