<?php
if ($suggestion->userId == $this->zfcUserIdentity()->getId()) {
    $btnEditClass = '';
} else {
    $btnEditClass = 'disabled';
}

if ($suggestion->voteCount > 0) {
    $btnVoteClass = 'btn-success';
    $vote = 0;
} else {
    $btnVoteClass = 'btn-default';
    $vote = 1;
}
?>
<div class="btn-group" style="display:flex" role="group">
<?php if ($this->isGranted('suggestion.accept')) : ?>
  <button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="<?= $this->escapeHtmlAttr($this->translate('Accept')) ?>" role="button"><i class="fa fa-check-square-o fa-fw" aria-hidden="true"></i></button>
<?php endif; ?>
<?php if ($this->isGranted('suggestion.edit')) : ?>
  <button type="button" class="btn btn-default <?= $btnEditClass ?> suggestionEdit" data-toggle="tooltip" data-placement="bottom" data-entryid="<?= $entryId ?>" data-suggestionid="<?= $suggestion->id ?>" data-suggestion="<?= $this->escapeHtmlAttr(json_encode($suggestion)) ?>" title="<?= $this->escapeHtmlAttr($this->translate('Edit')) ?>" role="button"><i class="fa fa-pencil-square-o fa-fw" aria-hidden="true"></i></button>
<?php endif; ?>
<?php if ($this->isGranted('suggestion.vote')) : ?>
  <button type="button" class="btn <?= $btnVoteClass ?> suggestionVote" data-toggle="tooltip" data-placement="bottom" data-entryid="<?= $entryId ?>" data-suggestionid="<?= $suggestion->id ?>" data-vote="<?= $vote ?>" title="<?= $this->escapeHtmlAttr($this->translate('Vote')) ?>" role="button"><i class="fa fa-thumbs-o-up fa-fw" aria-hidden="true"></i></button>
<?php endif; ?>
</div>
