<?php
if ($suggestion->voteCount > 0) {
    $btnClass = 'btn-success';
} else {
    $btnClass = 'btn-default';
}
?>
                <tr id="suggestion-<?= $suggestion->id?>">
                  <td>
<?php if ($type == 'String'): ?>
<?= nl2br($this->escapeHtml($suggestion->value)) ?>
<?php endif; ?>
                  </td>
                  <td class="text-right"><?= $suggestion->voteCountAll ?></td>
                  <td>
                    <div class="btn-group" style="display:flex" role="group">
                      <button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="<?= $this->escapeHtmlAttr($this->translate('Accept')) ?>" role="button"><span class="glyphicon glyphicon-check" aria-hidden="true"></span></button>
                      <button type="button" class="btn <?= $btnClass ?>" data-toggle="tooltip" data-placement="bottom" title="<?= $this->escapeHtmlAttr($this->translate('Vote')) ?>" role="button"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></button>
                    </div>
                  </td>
                </tr>
