<div>
<?php if ($entry->defaultLastChange > $entry->lastChange): ?>
  <div class="pull-right text-warning">
    <i class="fa fa-exclamation-triangle fa-fw" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="<?= $this->escapeHtmlAttr($this->translate('Default value is newer than translation. Please check.')) ?>"></i>
  </div>
<?php endif; ?>
<?php if ($entry->resourceTypeId == array_search('string', $resourceTypes)): ?>
<?= nl2br($this->escapeHtml($entry->value)) ?>
<?php endif; ?>
</div>