<?php
if ($entry->suggestionCount > 0) {
    $btnClass = 'btn-info';
} elseif (($entry->notificationStatus == 2) && $markApprovedTranslationsGreen) {
    $btnClass = 'btn-success';
} elseif ($entry->notificationStatus == 1) {
    $btnClass = 'btn-warning';
} else {
    $btnClass = 'btn-default';
}
$tooltip = sprintf($this->translatePlural('%d suggestion', '%d suggestions', $entry->suggestionCount), $entry->suggestionCount);
?>
<div class="btn-group" role="group">
  <button type="button" class="btn <?= $btnClass ?> translationDetails" data-entryid="<?= $this->escapeHtmlAttr($entry->defaultId) ?>" data-toggle="tooltip" data-placement="bottom" title="<?= $this->escapeHtmlAttr($tooltip) ?>" role="button"><i class="fa fa-list fa-fw" aria-hidden="true"></i> <?= $this->escapeHtml($this->translate('Details')) ?></button>
</div>