<?php
$data = [];
foreach ($suggestions as $suggestion) {
    $partialData = [
        'entryId' => $entry->defaultId,
        'suggestion' => $suggestion,
        'type' => $type,
    ];
    $data[] = [
        'suggestionId' => $suggestion->id,
        'suggestion' => $this->partial('translations/translations/partial/details-suggestion-suggestion.phtml', $partialData),
        'votes' => $suggestion->voteCountAll,
        'buttons' => $this->partial('translations/translations/partial/details-suggestion-buttons.phtml', $partialData),
    ];
}
?>
<div class="modal fade" id="modalDetails" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel"><?= $this->escapeHtml($this->translate('Translations details')) ?></h4>
      </div>
      <div class="modal-body">
        <div class="modal-spinner">
          <i class="fa fa-spinner fa-pulse fa-4x fa-fw" aria-hidden="true"></i>
        </div>
        <div class="row">
          <div class="col-lg-3"><b><?= $this->escapeHtml($this->translate('Default value:')) ?></b></div>
          <div class="col-lg-9">
<?php if ($type == 'String'): ?>
<?= nl2br($this->escapeHtml($entry->defaultValue)) ?>
<?php endif; ?>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"><hr></div>
        </div>
        <div class="row">
          <div class="col-lg-3"><b><?= $this->escapeHtml($this->translate('Current value:')) ?></b></div>
          <div class="col-lg-9">
<?php if ($type == 'String'): ?>
<?= nl2br($this->escapeHtml($entry->value)) ?>
<?php endif; ?>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"><hr></div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <b><?= $this->escapeHtml($this->translate('Suggestions:')) ?></b>
            <table class="table table-condensed table-striped" id="suggestions">
              <thead>
                <tr>
                  <th><?= $this->escapeHtml($this->translate('Value')) ?></th>
                  <th><?= $this->escapeHtml($this->translate('Votes')) ?></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
<?php if ($this->isGranted('suggestion.add')) : ?>
          <div class="col-lg-12"><button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Add new suggestion')) ?></button></div>
<?php endif; ?>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="fa fa-times" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Close')) ?></button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
//<!--
    var suggestionData = <?= json_encode($data) ?>;
//-->
</script>