<div class="modal fade" id="modalDetails" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel"><?= $this->escapeHtml($this->translate('Translations details')) ?></h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-3"><b><?= $this->escapeHtml($this->translate('Default value:')) ?></b></div>
          <div class="col-lg-9">
<?php if ($type == 'String'): ?>
<?= nl2br($this->escapeHtml($entry->defaultValue)) ?>
<?php endif; ?>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"><hr></div>
        </div>
        <div class="row">
          <div class="col-lg-3"><b><?= $this->escapeHtml($this->translate('Current value:')) ?></b></div>
          <div class="col-lg-9">
<?php if ($type == 'String'): ?>
<?= nl2br($this->escapeHtml($entry->value)) ?>
<?php endif; ?>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"><hr></div>
        </div>
        <div class="row">
<?php if ($entry->suggestionCount > 0): ?>
          <div class="col-lg-12">
            <b><?= $this->escapeHtml($this->translate('Suggestions:')) ?></b>
            <table class="table table-condensed table-striped">
              <thead>
                <tr>
                  <th><?= $this->escapeHtml($this->translate('Value')) ?></th>
                  <th><?= $this->escapeHtml($this->translate('Votes')) ?></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
<?php foreach ($suggestions as $suggestion): ?>
                <tr>
                  <td>
<?php if ($type == 'String'): ?>
<?= nl2br($this->escapeHtml($suggestion->value)) ?>
<?php endif; ?>
                  </td>
                  <td></td>
                  <td></td>
                </tr>
<?php endforeach; ?>
              </tbody>
            </table>
          </div>
<?php else: ?>
          <div class="col-lg-3"><b><?= $this->escapeHtml($this->translate('Suggestions:')) ?></b></div>
          <div class="col-lg-9"><?= $this->escapeHtml($this->translate('No entries available')) ?></div>
<?php endif; ?>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary"><?= $this->escapeHtml($this->translate('Add new suggestion')) ?></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->escapeHtml($this->translate('Close')) ?></button>
      </div>
    </div>
  </div>
</div>