<?php
$title = $this->translate('Translations');
$this->headTitle($title);
$this->bootstrapSelectHelper();
$this->dataTablesInitHelper([
    'table'   => '#translations',
    'options' => [
        'columnDefs' => [
            [
                'data'       => 'name',
                'orderable'  => false,
                'searchable' => true,
                'targets'    => 0,
                'visible'    => false,
            ],
            [
                'data'       => 'product',
                'orderable'  => false,
                'searchable' => true,
                'targets'    => 1,
                'visible'    => false,
            ],
            [
                'data'       => 'nameView',
                'orderable'  => true,
                'orderData'  => [0, 1],
                'searchable' => false,
                'targets'    => 2,
                'visible'    => true,
            ],
            [
                'data'       => 'defaultValue',
                'orderable'  => true,
                'searchable' => true,
                'targets'    => 3,
                'visible'    => true,
            ],
            [
                'data'       => 'translatedValue',
                'orderable'  => true,
                'searchable' => true,
                'targets'    => 4,
                'visible'    => true,
            ],
            [
                'data'       => 'buttons',
                'orderable'  => false,
                'searchable' => false,
                'targets'    => 5,
                'visible'    => true,
            ],
        ],
        'order' => [
            [2, 'asc'],
        ],
        'rowId' => 'defaultId',
    ],
]);

$this->dataTablesInitHelper([
    'table'   => '#suggestions',
    'options' => [
        'columnDefs' => [
            [
                'data'       => 'suggestion',
                'orderable'  => true,
                'searchable' => true,
                'targets'    => 0,
                'visible'    => true,
            ],
            [
                'data'       => 'votes',
                'orderable'  => true,
                'searchable' => true,
                'targets'    => 1,
                'visible'    => true,
                'width'      => '10%'
            ],
            [
                'data'       => 'buttons',
                'orderable'  => false,
                'searchable' => false,
                'targets'    => 2,
                'visible'    => true,
                'width'      => '10%'
            ],
        ],
        'rowId' => 'suggestionId',
        'autoWidth' => true,
    ],
], 'initSuggestions');

$min = ($this->useMinified()) ? '.min' : '';

$this->inlineScript()->appendScript('var apps = ' . json_encode($apps) . ';
var resources = ' . json_encode($resources) . ';
var appsAll = ' . json_encode($appsAll) . ';
var resourcesAll = ' . json_encode($resourcesAll) . ';
var translationsPath = "' . $this->url('translations/listtranslations'). '";
var detailsPath = "' . $this->url('translations/details'). '";
var suggestionvotePath = "' . $this->url('translations/suggestionvote'). '";')->appendFile($this->basePath('js/translations' . $min . '.js'));
?>
<div id="modalContainer"></div>
<div class="modal fade" id="modalError" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel"><?= $this->escapeHtml($this->translate('Error')) ?></h4>
      </div>
      <div class="modal-body">
        <?= $this->escapeHtml($this->translate('An unexpected error has occurred while loading the translation details.')) ?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->escapeHtml($this->translate('Close')) ?></button>
      </div>
    </div>
  </div>
</div>
<div class="row" id="header">
  <div class="col-lg-12">
    <h1><?= $this->escapeHtml($title) ?></h1>
  </div>
</div>
<form method="post" name="appAndResourceSelection">
<?php if ($this->isGranted('team.viewAll')): ?>
  <div class="row">
    <div class="col-lg-12">
      <div class="checkbox">
        <label>
          <input type="checkbox" id="showAll"> <?= $this->escapeHtml($this->translate('Show all')) ?>
        </label>
      </div>
    </div>
  </div>
<?php endif; ?>
  <div class="row" id="selection">
    <div class="col-lg-6">
      <div class="form-group">
        <label class="control-label" for="app"><?= $this->escapeHtml($this->translate('App')) ?></label>
        <select name="app" class="form-control selectpicker" data-live-search="true" multiple data-max-options="1" id="app">
<?php foreach($apps as $key => $value): ?>
          <option value="<?= $this->escapeHtmlAttr($key) ?>"><?= $this->escapeHtml($value) ?></option>
<?php endforeach; ?>
        </select>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group">
        <label class="control-label" for="resource"><?= $this->escapeHtml($this->translate('Resource')) ?></label>
        <select name="resource" class="form-control selectpicker" data-live-search="true" multiple data-max-options="1" id="resource">
        </select>
      </div>
    </div>
  </div>
</form>
<div class="row" id="selectionHint">
  <div class="col-lg-12">
    <?= $this->escapeHtml($this->translate('Please select app and resource.')) ?>
  </div>
</div>
<div class="row hidden" id="spinner">
  <div class="col-lg-12 text-center">
    <i class="fa fa-spinner fa-pulse fa-4x fa-fw" aria-hidden="true"></i>
  </div>
</div>
<div class="row hidden" id="translationRow">
  <div class="col-lg-12 ">
    <table class="table table-bordered table-striped" id="translations">
      <thead>
        <tr>
          <th>name</th>
          <th>product</th>
          <th><?= $this->escapeHtml($this->translate('Name')) ?></th>
          <th><?= $this->escapeHtml($this->translate('Default value')) ?></th>
          <th><?= $this->escapeHtml($this->translate('Translation')) ?></th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>
