<?php
$title = $this->translate('Translations');
$this->headTitle($title);
$this->bootstrapSelectHelper();
$this->dataTablesInitHelper([
    'table'   => '#translations',
    'options' => [
        'columnDefs' => [
            [
                'data'       => 'name',
                'orderable'  => true,
                'searchable' => true,
                'targets'    => 0,
                'visible'    => true,
            ],
            [
                'data'       => 'defaultValue',
                'orderable'  => true,
                'searchable' => true,
                'targets'    => 1,
                'visible'    => true,
            ],
            [
                'data'       => 'translatedValue',
                'orderable'  => true,
                'searchable' => true,
                'targets'    => 2,
                'visible'    => true,
            ],
            [
                'data'       => 'buttons',
                'orderable'  => false,
                'searchable' => false,
                'targets'    => 3,
                'visible'    => true,
            ],
        ],
        'order' => [
            [0, 'asc'],
        ],
        'rowId' => 'defaultId',
    ],
]);

$this->inlineScript()->appendScript('var apps = ' . json_encode($apps) . ';
var resources = ' . json_encode($resources) . ';
var appsAll = ' . json_encode($appsAll) . ';
var resourcesAll = ' . json_encode($resourcesAll) . ';
var translationsPath = "' . $this->url('translations', [
    'action' => 'listtranslations',
]). '";')->appendFile($this->basePath('js/translations.min.js'));
?>
<div class="row" id="header">
  <div class="col-lg-12">
    <h1><?= $this->escapeHtml($title) ?></h1>
  </div>
</div>
<form method="post" name="appAndResourceSelection">
<?php if ($this->isGranted('team.viewAll')): ?>
  <div class="row">
    <div class="col-lg-12">
      <div class="checkbox">
        <label>
          <input type="checkbox" id="showAll"> <?= $this->escapeHtml($this->translate('Show all')) ?>
        </label>
      </div>
    </div>
  </div>
<?php endif; ?>
  <div class="row" id="selection">
    <div class="col-lg-6">
      <div class="form-group">
        <label class="control-label" for="app"><?= $this->escapeHtml($this->translate('App')) ?></label>
        <select name="app" class="form-control selectpicker" data-live-search="true" multiple data-max-options="1" id="app">
<?php foreach($apps as $key => $value): ?>
          <option value="<?= $this->escapeHtmlAttr($key) ?>"><?= $this->escapeHtml($value) ?></option>
<?php endforeach; ?>
        </select>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group">
        <label class="control-label" for="resource"><?= $this->escapeHtml($this->translate('Resource')) ?></label>
        <select name="resource" class="form-control selectpicker" data-live-search="true" multiple data-max-options="1" id="resource">
        </select>
      </div>
    </div>
  </div>
</form>
<div class="row" id="selectionHint">
  <div class="col-lg-12">
    <?= $this->escapeHtml($this->translate('Please select app and resource.')) ?>
  </div>
</div>
<div class="row hidden" id="spinner">
  <div class="col-lg-12 text-center">
    <i class="fa fa-spinner fa-pulse fa-4x fa-fw" aria-hidden="true"></i>
  </div>
</div>
<div class="row hidden" id="translationRow">
  <div class="col-lg-12 ">
    <table class="table table-bordered table-striped" id="translations">
      <thead>
        <tr>
          <th><?= $this->escapeHtml($this->translate('Name')) ?></th>
          <th><?= $this->escapeHtml($this->translate('Default value')) ?></th>
          <th><?= $this->escapeHtml($this->translate('Translation')) ?></th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>
