<?php
$title = $this->translate('Translations');
$this->headTitle($title);
$this->bootstrapSelectHelper();
$this->dataTablesInitHelper(['table' => '#translations']);
?>
<div class="row" id="header">
  <div class="col-lg-12">
    <h1><?= $this->escapeHtml($title) ?></h1>
  </div>
</div>
<form method="post" name="appAndResourceSelection">
  <div class="row" id="selection">
    <div class="col-lg-6">
      <div class="form-group">
        <label class="control-label" for="app"><?= $this->escapeHtml($this->translate('App')) ?></label>
        <select name="app" class="form-control selectpicker" data-live-search="true" id="app">
        </select>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="form-group">
        <label class="control-label" for="resource"><?= $this->escapeHtml($this->translate('Resource')) ?></label>
        <select name="resource" class="form-control selectpicker" data-live-search="true" id="resource">
        </select>
      </div>
    </div>
  </div>
</form>
<div class="row" id="selectionHint">
  <div class="col-lg-12">
    <?= $this->escapeHtml($this->translate('Please select app and resource.')) ?>
  </div>
</div>
<div class="row hidden" id="spinner">
  <div class="col-lg-12 text-center">
    <i class="fa fa-spinner fa-pulse fa-4x fa-fw" aria-hidden="true"></i>
  </div>
</div>
<div class="row hidden" id="translationRow">
  <div class="col-lg-12 ">
    <table class="table table-bordered table-striped" id="translations">
      <thead>
        <tr>
          <th><?= $this->escapeHtml($this->translate('Default')) ?></th>
          <th><?= $this->escapeHtml($this->translate('Translation')) ?></th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody id="translationTableBody">
      </tbody>
    </table>
  </div>
</div>
