<?php
$title = $this->translate('Delete team');
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<div>
<?php
foreach ($messages as $message) {
    echo $this->partial('partial/alert.phtml', [
        'type'     => $message['type'],
        'message'  => $message['message'],
        'canClose' => $message['canClose'],
    ]);
}
?>
</div>
<p><?= $this->escapeHtml(sprintf($this->translate('Are you sure that you want to delete the team "%s"?'), $team->Name)) ?></p>
<?php
$form->setAttribute('action', $this->url('team', [
    'action' => 'delete',
    'id'     => $team->Id,
]));
echo $this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
?>
