<?= $this->doctype() ?>

<html lang="<?= \Locale::getPrimaryLanguage($this->plugin('translate')->getTranslator()->getLocale()) ?>">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Translation Manager for Android Apps')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/Ætoms_-_Translation.svg') ?>" height="28" alt=""/>&nbsp;Translation Manager for Android Apps
                    </a>
                </div>
                <div class="collapse navbar-collapse">
<?php if($this->zfcUserIdentity()): ?>
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Home')) ?></a></li>
                    </ul>
<?php endif; ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2017<?php if ((int)date('Y') > 2017) echo ' - ' . date('Y') ?> by Andrej Sinicyn. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
