<?= $this->doctype() ?>

<html lang="<?= \Locale::getPrimaryLanguage($this->plugin('translate')->getTranslator()->getLocale()) ?>">
  <head>
    <meta charset="utf-8">
    <?= $this->headTitle('Translation Manager for Android Apps')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/style.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
    ?>

  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?= $this->url('home') ?>">
            <img src="<?= $this->basePath('img/Ætoms_-_Translation.svg') ?>" height="28" alt=""/>&nbsp;Translation Manager for Android Apps
          </a>
        </div>
        <div class="collapse navbar-collapse">
<?php
if ($this->zfcUserIdentity()) {
    echo $this->multilevelNavigationMenu('navigation', 'partial/menu-dropdown.phtml');
}
?>
        </div>
      </div>
    </nav>
    <div class="container">
      <?= $this->content ?>
      <hr>
      <footer>
        <p>&copy; 2017<?php if ((int)date('Y') > 2017) echo ' - ' . date('Y') ?> by Andrej Sinicyn. All rights reserved.</p>
      </footer>
    </div>
    <?= $this->inlineScript() ?>

  </body>
</html>
