<?php
$title = $this->translate('Apps');
$this->headTitle($title);
$this->dataTablesInitHelper(['table' => '#apps']);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php if ($this->isGranted('app.add')) : ?>
<p>
    <a class="btn btn-default" href="<?= $this->url('app', ['action' => 'add']) ?>"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Add new app')) ?></a>
</p>
<?php endif; ?>
<table class="table table-bordered table-striped" id="apps">
    <thead>
        <tr>
<?php if (count($teams) > 1) : ?>
            <th><?= $this->escapeHtml($this->translate('Team')) ?></th>
<?php endif; ?>
            <th><?= $this->escapeHtml($this->translate('Name')) ?></th>
            <th><?= $this->escapeHtml($this->translate('Git repository')) ?></th>
            <th><?= $this->escapeHtml($this->translate('Path to "res" folder')) ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($apps as $app) : ?>
        <tr>
<?php if (count($teams) > 1) : ?>
            <td><?= $this->escapeHtml((array_key_exists($app->teamId, $teams) ? $teams[$app->teamId] : $app->teamId)) ?></td>
<?php endif; ?>
            <td><?= $this->escapeHtml($app->name) ?></td>
            <td><?= $this->escapeHtml($app->gitRepository) ?></td>
            <td><?= $this->escapeHtml($app->pathToResFolder) ?></td>
            <td>
                <div class="btn-group">
<?php if ($this->isGranted('app.edit')) : ?>
                    <a class="btn btn-default" href="<?= $this->url('app', ['action' => 'edit', 'id' => $app->id]) ?>"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Edit')) ?></a>
<?php endif; ?>
<?php if ($this->isGranted('app.delete')) : ?>
                    <a class="btn btn-danger" href="<?= $this->url('app', ['action' => 'delete', 'id' => $app->id]) ?>"><span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Delete')) ?></a>
<?php endif; ?>
                </div>
            </td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>