<?php
$title = $this->translate('Apps');
$this->headTitle($title);
$this->dataTablesInitHelper(['table' => '#apps']);
$printTeams = count($teams) > 1;
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php if ($this->isGranted('app.add')) : ?>
<p>
  <a class="btn btn-default" href="<?= $this->url('app', [
    'action' => 'add',
]) ?>"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Add new app')) ?></a>
</p>
<?php endif; ?>
<table class="table table-bordered table-striped" id="apps">
  <thead>
    <tr>
<?php if ($printTeams) : ?>
      <th><?= $this->escapeHtml($this->translate('Team')) ?></th>
<?php endif; ?>
      <th><?= $this->escapeHtml($this->translate('Name')) ?></th>
      <th><?= $this->escapeHtml($this->translate('Path to "res" folder')) ?></th>
      <th><?= $this->escapeHtml($this->translate('Git repository')) ?></th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($apps as $app) : ?>
    <tr>
<?php if ($printTeams) : ?>
      <td><?= $this->escapeHtml((array_key_exists($app->teamId, $teams) ? $teams[$app->TeamId] : $app->TeamId)) ?></td>
<?php endif; ?>
      <td><?= $this->escapeHtml($app->Name) ?></td>
      <td><?= $this->escapeHtml($app->PathToResFolder) ?></td>
      <td><?= $this->escapeHtml($app->GitRepository) ?></td>
      <td>
        <div class="btn-group">
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Tasks')) ?> <span class="caret"></span></button>
            <ul class="dropdown-menu">
<?php if ($this->isGranted('git') && (strlen($app->GitRepository) > 0)) : ?>
              <li><a href="<?= $this->url('git', [
    'appId'  => $app->id,
    'action' => 'index',
]) ?>"><span class="fa fa-git" aria-hidden="true"></span> <?= $this->escapeHtml('Git') ?></a></li>
<?php endif; ?>
<?php if ($this->isGranted('sync')) : ?>
              <li><a href="<?= $this->url('sync', [
    'appId'  => $app->id,
    'action' => 'index',
]) ?>"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Sync')) ?></a></li>
<?php endif; ?>
<?php if ($this->isGranted('appresource.view') || $this->isGranted('appresourcefile.view')) : ?>
              <li role="separator" class="divider"></li>
<?php endif; ?>
<?php if ($this->isGranted('appresource.view')) : ?>
              <li><a href="<?= $this->url('appresource', [
    'appId' => $app->Id,
]) ?>"><span class="glyphicon glyphicon-file" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Resources')) ?>  <span class="badge"><?= (int) $app->ResourceCount ?></span></a></li>
<?php endif; ?>
<?php if ($this->isGranted('appresourcefile.view')) : ?>
              <li><a href="<?= $this->url('appresourcefile', [
    'appId' => $app->Id,
]) ?>"><span class="fa fa-file-text" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Resource files')) ?>  <span class="badge"><?= (int) $app->ResourceFileCount ?></span></a></li>
<?php endif; ?>
            </ul>
          </div>
<?php if ($this->isGranted('app.edit')) : ?>
          <a class="btn btn-default" href="<?= $this->url('app', [
    'action' => 'edit',
    'id'     => $app->Id,
]) ?>"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Edit')) ?></a>
<?php endif; ?>
<?php if ($this->isGranted('app.delete')) : ?>
          <a class="btn btn-danger" href="<?= $this->url('app', [
    'action' => 'delete',
    'id'     => $app->id,
]) ?>"><span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Delete')) ?></a>
<?php endif; ?>
        </div>
      </td>
    </tr>
<?php endforeach; ?>
  </tbody>
</table>
