<?php
$title = sprintf($this->translate('Add members to team "%s"'), $team->name);
$this->headTitle($title);
$form->setAttribute('action', $this->url('teammember', [
    'teamId' => $team->id,
    'action' => 'add',
]));
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php if ($this->isGranted('teammember.view')) : ?>
<p>
  <a class="btn btn-default" href="<?= $this->url('teammember', [
    'teamId' => $team->Id,
    'action' => 'index',
]) ?>"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Back')) ?></a>
</p>
<?php endif; ?>
<?php if ($this->isGranted('teammember.add')) : ?>
<?php $this->dataTablesInitHelper(['table' => '#usersNotInTeam']); ?>
<div><?= $this->message ?></div>
<table class="table table-bordered table-striped" id="usersNotInTeam">
  <thead>
    <tr>
      <th><?= $this->escapeHtml($this->translate('Username')) ?></th>
      <th><?= $this->escapeHtml($this->translate('Email')) ?></th>
      <th><?= $this->escapeHtml($this->translate('Display name')) ?></th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($usersNotInTeam as $user) : ?>
    <tr>
      <td><?= $this->escapeHtml($user->Username) ?></td>
      <td><?= $this->escapeHtml($user->Email) ?></td>
      <td><?= $this->escapeHtml($user->DisplayName) ?></td>
      <td>
<?php
$teamMember = new \Translations\Model\TeamMember([
    'user_id' => $user->UserId,
    'team_id' => $team->Id,
]);
$form->bind($teamMember);
echo $this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_INLINE);
?>
      </td>
    </tr>
<?php endforeach; ?>
  </tbody>
</table>
<?php endif; ?>
