<?php
$title = sprintf($this->translate('Remove team member with email "%s"'), $teamMember->email);
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p><?= $this->escapeHtml(sprintf($this->translate('Are you sure that you want to remove the team team member with email "%s" from the team "%s"?'), $teamMember->email, $teamMember->teamName)) ?></p>
<?php
$form->setAttribute('action', $this->url('teammember', [
    'teamId' => $teamMember->teamId,
    'action' => 'remove',
    'userId' => $teamMember->userId,
]));
echo $this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
?>
