<?php
    $formStep1 = $this->formStep1;
    $formStep1->setAttribute('action', $this->url('setup'));
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= $this->escapeHtml($this->translate('Setup')) ?> - <?= $this->escapeHtml(sprintf($this->translate('Step %d'), 1)) ?></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-2">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation" class="active"><a id="step1" href="#"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 1)) ?></a></li>
            <li role="presentation" class="disabled"><a id="step2" href="#"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 2)) ?></a></li>
        </ul>
    </div>
    <div class="col-lg-10">
        <h3><?= $this->escapeHtml($this->translate('Welcome to the setup routine.')) ?></h3>
        <div><?= $this->form($formStep1, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL); ?></div>
    </div>
</div>
