<div class="jumbotron">
    <h1>Setup</h1>
</div>

<div class="row">
    <div class="col-lg-2">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation" class="active"><a href="#">Introduction</a></li>
        </ul>
    </div>
    <div class="col-lg-10">
        <h1 class="page-header">Introduction</h1>
        <p>Welcome to the setup routine.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Begin Setup</a></p>
    </div>
</div>
