<?php
    $formStep2->setAttribute('action', $this->url('setup', ['action' => 'step2']));

    $this->inlineScript()->appendScript('
$("#back").on("click", function () {
    var url = "' . $this->url('setup') . '";
    $(location).attr("href", url);
});
$("#testConnection").on("click", function () {
    var url = "' . $this->url('setup', ['action' => 'databaseconnectiontest']) . '";
    var post = $("#formStep2").serialize();
    try {
        $.post(url, post, function(data) {
            if (data.html) {
                $("#step2StatusCheck").prepend(data.html);
            } else {
                $("#step2StatusCheck").prepend("<div>" + data + "</div>");
            }
        }, "json").fail(function() {
                $("#step2StatusCheck").prepend("' . $this->escapeHtml($this->translate('An error occured during AJAX request.')) . '");
            }
        );
    } catch(ex) {
        $("#step2StatusCheck").prepend("<div>" + ex.message + "</div>");
    }
})');
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= $this->escapeHtml($this->translate('Setup')) ?>: <?= $this->escapeHtml(sprintf($this->translate('Step %d'), 2)) ?> &ndash; <?= $this->escapeHtml($this->translate('Database'))?></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-3">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation"><a id="step1" href="<?= $this->url('setup') ?>"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 1)) ?> &ndash; <?= $this->escapeHtml($this->translate('Language'))?></a></li>
            <li role="presentation" class="active"><a id="step2" href="#"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 2)) ?> &ndash; <?= $this->escapeHtml($this->translate('Database'))?></a></li>
            <li role="presentation" class="disabled"><a id="step3" href="#"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 3)) ?> &ndash; <?= $this->escapeHtml($this->translate('Database schema'))?></a></li>
            <li role="presentation" class="disabled"><a id="step4" href="#"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 4)) ?> &ndash; <?= $this->escapeHtml($this->translate('User creation'))?></a></li>
        </ul>
    </div>
    <div class="col-lg-9">
        <h3><?= $this->escapeHtml($this->translate('Database setup')) ?></h3>
        <div id="step2StatusCheck"></div>
        <div><?= $this->form($formStep2, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL); ?></div>
    </div>
</div>
