<?php
    $formStep2 = $this->formStep2;
    $formStep2->setAttribute('action', $this->url('setup/step2'));
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= $this->escapeHtml($this->translate('Setup')) ?> - <?= $this->escapeHtml(sprintf($this->translate('Step %d'), 2)) ?></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-2">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation"><a id="step1" href="<?= $this->url('setup/step1') ?>"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 1)) ?></a></li>
            <li role="presentation" class="active"><a id="step2" href="#"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 2)) ?></a></li>
        </ul>
    </div>
    <div class="col-lg-10">
        <p><?= $this->escapeHtml($this->translate('Database setup')) ?></p>
        <p><?= $this->form($formStep2, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL); ?></p>
    </div>
</div>
