<?php
    $formStep3 = $this->formStep3;
    $formStep3->setAttribute('action', $this->url('setup', ['action' => 'step3']));
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= $this->escapeHtml($this->translate('Setup')) ?>: <?= $this->escapeHtml(sprintf($this->translate('Step %d'), 2)) ?> &ndash; <?= $this->escapeHtml($this->translate('Database schema'))?></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-3">
        <ul class="nav nav-pills nav-stacked">
            <li role="presentation"><a id="step1" href="<?= $this->url('setup') ?>"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 1)) ?> &ndash; <?= $this->escapeHtml($this->translate('Language'))?></a></li>
            <li role="presentation"><a id="step2" href="<?= $this->url('setup', ['action' => 'step2']) ?>"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 2)) ?> &ndash; <?= $this->escapeHtml($this->translate('Database'))?></a></li>
            <li role="presentation" class="active"><a id="step3" href="#"><?= $this->escapeHtml(sprintf($this->translate('Step %d'), 2)) ?> &ndash; <?= $this->escapeHtml($this->translate('Database schema'))?></a></li>
        </ul>
    </div>
    <div class="col-lg-9">
        <h3><?= $this->escapeHtml($this->translate('Database schema installation')) ?></h3>
        <div id="step2StatusCheck"></div>
        <div><?= $this->form($formStep3, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL); ?></div>
    </div>
</div>
