<?php
$title = sprintf($this->translate('Edit resource of app "%s"'), $app->Name);
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('appresource', [
    'appId'      => $appResource->AppId,
    'action'     => 'edit',
    'resourceId' => $appResource->Id,
]));
echo $this->form($form, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
?>
