<?php
$title = sprintf($this->translate('Resources of app "%s"'), $app->name);
$this->headTitle($title);
$this->dataTablesInitHelper(['table' => '#appResources']);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php if ($this->isGranted('appresource.add')) : ?>
<p>
    <a class="btn btn-default" href="<?= $this->url('appresource', ['appId' => $app->id, 'action' => 'add']) ?>"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Add new app resource')) ?></a>
</p>
<?php endif; ?>
<table class="table table-bordered table-striped" id="appResources">
    <thead>
        <tr>
            <th><?= $this->escapeHtml($this->translate('Name')) ?></th>
            <th><?= $this->escapeHtml($this->translate('Locale')) ?></th>
            <th><?= $this->escapeHtml($this->translate('Description')) ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($appResources as $appResource) : ?>
        <tr>
            <td><?= $this->escapeHtml($appResource->name) ?></td>
            <td><?= $this->escapeHtml((array_key_exists($appResource->locale, $localeNames) ? $localeNames[$appResource->locale] : $appResource->locale)) ?></td>
            <td><?= $this->escapeHtml($appResource->description) ?></td>
            <td>
                <div class="btn-group">
<?php if ($this->isGranted('appresource.edit')) : ?>
                    <a class="btn btn-default" href="<?= $this->url('appresource', ['appId' => $app->id, 'action' => 'edit', 'resourceId' => $appResource->id]) ?>"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Edit')) ?></a>
<?php endif; ?>
<?php if ($this->isGranted('appresource.delete')) : ?>
                    <a class="btn btn-danger" href="<?= $this->url('appresource', ['appId' => $app->id, 'action' => 'delete', 'resourceId' => $appResource->id]) ?>"><span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Delete')) ?></a>
<?php endif; ?>
                </div>
            </td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>