<?php
$title = sprintf($this->translate('Resources of app "%s"'), $app->Name);
$this->headTitle($title);
$this->dataTablesInitHelper(['table' => '#appResources']);
$count = count($appResources);
$disable = !$hasDefaultValues;
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php if ($this->isGranted('appresource.add')) : ?>
<p>
  <a class="btn btn-default" href="<?= $this->url('appresource', [
    'appId'  => $app->Id,
    'action' => 'add',
]) ?>"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Add new app resource')) ?></a>
</p>
<?php endif; ?>
<table class="table table-bordered table-striped" id="appResources">
  <thead>
    <tr>
      <th><?= $this->escapeHtml($this->translate('Name')) ?></th>
      <th><?= $this->escapeHtml($this->translate('Locale')) ?></th>
      <th><?= $this->escapeHtml($this->translate('Description')) ?></th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
<?php foreach ($appResources as $appResource) : ?>
    <tr>
      <td><?= $this->escapeHtml($appResource->Name) ?></td>
      <td><?= $this->escapeHtml((array_key_exists($appResource->Locale, $localeNames) ? $localeNames[$appResource->Locale] : $appResource->Locale)) ?></td>
      <td><?= $this->escapeHtml($appResource->Description) ?></td>
      <td>
        <div class="btn-group">
<?php if ($this->isGranted('appresource.edit')) : ?>
          <a class="btn btn-default<?php if ($disable): ?> disabled<?php endif; ?>" href="<?= ($disable) ? '#' : $this->url('appresource', [
    'appId'      => $appResource->AppId,
    'action'     => 'edit',
    'resourceId' => $appResource->Id
]) ?>"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Edit')) ?></a>
<?php endif; ?>
<?php $disableDelete = $disable || (($count > 1) && ($appResource->name == 'values')); ?>
<?php if ($this->isGranted('appresource.delete')) : ?>
          <a class="btn btn-danger<?php if ($disableDelete): ?> disabled<?php endif; ?>" href="<?= ($disableDelete) ? '#' : $this->url('appresource', [
    'appId'      => $appResource->AppId,
    'action'     => 'delete',
    'resourceId' => $appResource->Id,
]) ?>"><span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span> <?= $this->escapeHtml($this->translate('Delete')) ?></a>
<?php endif; ?>
        </div>
      </td>
    </tr>
<?php endforeach; ?>
  </tbody>
</table>
