<?php
$title = sprintf($this->translate('Sync ressources of app "%s"'), $app->Name);
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><?= $this->escapeHtml($this->translate('Import resources')) ?></h3>
      </div>
      <div class="panel-body">
<?php
$formImport->setAttribute('action', $this->url('sync', [
    'appId'  => $app->Id,
    'action' => 'import',
]));
echo $this->form($formImport, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
?>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><?= $this->escapeHtml($this->translate('Export resources')) ?></h3>
      </div>
      <div class="panel-body">
<?php
$formExport->setAttribute('action', $this->url('sync', [
    'appId'  => $app->Id,
    'action' => 'export',
]));
echo $this->form($formExport, \TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL);
?>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="processingModal" tabindex="-1" role="dialog" aria-labelledby="processingModalLabel" data-backdrop="static">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="processingModalLabel"><?= $this->escapeHtml($this->translate('Processing...')) ?></h4>
      </div>
      <div class="modal-body text-center">
        <i class="fa fa-spinner fa-pulse fa-4x fa-fw" aria-hidden="true"></i>
      </div>
    </div>
  </div>
</div>
