<div class="row">
    <div class="col-md-12">
        <h1>Translation Manager for Android Apps <small>v<?= \Application\Module::VERSION ?></small></h1>
        <p class="lead">Licensed under <a href="https://www.gnu.org/licenses/gpl-3.0.en.html" target="_blank">GNU General Public License v3.0</a></p>
        <p>Icon by <a href="https://commons.wikimedia.org/wiki/User:%C3%86toms" target="_blank">Ætoms</a> licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">CC BY-SA 4.0</a></p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->escapeHtml($this->translate('Libraries')) ?></h2>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th><?= $this->escapeHtml($this->translate('Name')) ?></th>
                    <th><?= $this->escapeHtml($this->translate('License')) ?></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th><a href="https://framework.zend.com/" target="_blank">Zend Framework 3</a></th>
                    <th><a href="https://framework.zend.com/license" target="_blank">New BSD License</a></th>
                </tr>
                <tr>
                    <th><a href="https://getbootstrap.com/" target="_blank">Bootstrap 3</a></th>
                    <th><a href="https://github.com/twbs/bootstrap/blob/master/LICENSE" target="_blank">MIT License</a></th>
                </tr>
                <tr>
                    <th><a href="https://jquery.com/" target="_blank">jQuery 3</a></th>
                    <th><a href="https://jquery.org/license/" target="_blank">MIT License</a></th>
                </tr>
                <tr>
                    <th><a href="http://fontawesome.io/" target="_blank">FontAwesome 4</a></th>
                    <th><a href="http://fontawesome.io/license/" target="_blank">SIL OFL 1.1 / MIT License</a></th>
                </tr>
                <tr>
                    <th><a href="https://octicons.github.com/" target="_blank">Octicons 4</a></th>
                    <th><a href="https://github.com/primer/octicons/blob/master/LICENSE" target="_blank">MIT License</a></th>
                </tr>
            </tbody>
        </table>
    </div>
</div>
