<div class="row">
    <div class="col-md-12">
        <h1>Translation Manager for Android Apps <small>v<?= \Application\Module::VERSION ?></small></h1>
        <p class="lead">Licensed under <a href="https://www.gnu.org/licenses/gpl-3.0.en.html" target="_blank">GNU General Public License v3.0</a></p>
        <p>Icon by <a href="https://commons.wikimedia.org/wiki/User:%C3%86toms" target="_blank">Ætoms</a> licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">CC BY-SA 4.0</a></p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2><?= $this->escapeHtml($this->translate('Libraries')) ?></h2>
        <table class="table">
            <tr>
                <th><?= $this->escapeHtml($this->translate('Name')) ?></th>
                <th><?= $this->escapeHtml($this->translate('License')) ?></th>
            </tr>
            <tr>
                <th><a href="https://framework.zend.com/" target="_blank">Zend Framework 3</a></th>
                <th><a href="https://framework.zend.com/license" target="_blank">New BSD License</a></th>
            </tr>
        </table>
    </div>
</div>
