<div class="page-header">
    <h1><?= $this->escapeHtml(sprintf($this->translate('Hello, %s!'), $this->zfcUserDisplayName())) ?></h1>
</div>
<div class="btn-group">
    <a class="btn btn-default" href="<?= $this->url('zfcuser/changepassword') ?>"><?= $this->translate('Change password') ?></a>
    <a class="btn btn-default" href="<?= $this->url('zfcuser/changeemail') ?>"><?= $this->translate('Change email') ?></a>
    <a class="btn btn-default" href="<?= $this->url('zfcuser/logout') ?>"><?= $this->translate('Sign out') ?></a>
</div>