<div class="page-header">
  <h1><?= $this->escapeHtml(sprintf($this->translate('Hello, %s!'), $this->zfcUserDisplayName())) ?></h1>
</div>
<div class="btn-group">
  <a class="btn btn-default" href="<?= $this->url('settings/userlanguages') ?>"><i class="fa fa-language fa-fw" aria-hidden="true"></i> <?= $this->translate('My languages') ?></a>
</div>
<hr>
<div class="btn-group">
  <a class="btn btn-default" href="<?= $this->url('zfcuser/changepassword') ?>"><i class="fa fa-key fa-fw" aria-hidden="true"></i> <?= $this->translate('Change password') ?></a>
  <a class="btn btn-default" href="<?= $this->url('zfcuser/changeemail') ?>"><i class="fa fa-envelope fa-fw" aria-hidden="true"></i> <?= $this->translate('Change email') ?></a>
  <a class="btn btn-default" href="<?= $this->url('zfcuser/logout') ?>"><i class="fa fa-sign-out fa-fw" aria-hidden="true"></i> <?= $this->translate('Sign out') ?></a>
</div>
