<div class="page-header">
  <h1><?= $this->escapeHtml(sprintf($this->translate('Hello, %s!'), $this->zfcUserDisplayName())) ?></h1>
</div>
<div class="btn-group">
  <a class="btn btn-default" href="<?= $this->url('settings/userlanguages') ?>"><span class="fa fa-language" aria-hidden="true"></span> <?= $this->translate('My languages') ?></a>
</div>
<hr>
<div class="btn-group">
  <a class="btn btn-default" href="<?= $this->url('zfcuser/changepassword') ?>"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> <?= $this->translate('Change password') ?></a>
  <a class="btn btn-default" href="<?= $this->url('zfcuser/changeemail') ?>"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <?= $this->translate('Change email') ?></a>
  <a class="btn btn-default" href="<?= $this->url('zfcuser/logout') ?>"><span class="glyphicon glyphicon-off" aria-hidden="true"></span> <?= $this->translate('Sign out') ?></a>
</div>
